### ISSUE TITLE
Moshi 1.8 and Okio 2.0.0 crash

### ISSUE THREAD

**Issue by Tolriq** [square/moshi#740]
Moshi 1.8 works with Okio 2.1.0 but not 2.0.0.
It crashes with

```
    java.lang.NoSuchMethodError: No interface method getBuffer()Lokio/Buffer; in class Lokio/BufferedSource; or its super classes (declaration of 'okio.BufferedSource' appears in /data/app/xxx.debug-olbMLpTAtoCxjC1ETwuHHw==/base.apk!classes2.dex)
        at com.squareup.moshi.JsonUtf8Reader.<init>(JsonUtf8Reader.java:97)
        at com.squareup.moshi.JsonReader.of(JsonReader.java:196)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:36)
        at com.genimee.android.yatse.json.JsonApiMethod.convertResult(JsonApiMethod.kt:20)
        at com.genimee.android.yatse.json.JsonApiConnection.apiCall(JsonApiConnection.kt:205)
        at com.genimee.android.yatse.json.JsonApiConnection$apiCall$1.invokeSuspend(Unknown Source:13)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```
(May worth a note in changelog)
Unfortunately for me I had to go back to Okio 2.0.0 due to https://github.com/square/okio/issues/516 and R8 having a blocking issue with my app that is not solved :(

Since I'm touched by https://github.com/square/moshi/issues/679 I'd like to know if there could be an easy workaround for this crash as I'd like to move to 1.8.

I also already have migrated my direct Okio usage to the 2.x kotlin way, so can't really go back to 1.16 either.

**Comment by swankjesse** [comment]
Moshi 1.8 requires either Okio 2.1+ or Okio 1.16+. For each of these other issues it’s unclear what action we should take.

**Comment by swankjesse** [comment]
No action to take on this.

**Comment by Tolriq** [comment]
Maybe just update the changelog.

>  We don't yet require Kotlin-friendly Okio 2.x but Moshi works fine with that release.

Made me try with 2.0.0
